title: "dSociety"
description: "dSociety"
baseurl: ""
url: "https://www.dsociety.io"
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: default
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  guides:
    output: true
    permalink: /learn/:path/
    layout: learn
